name: giggles-is-you
version: 0.1

ghc-options:
  - -Wall
  - -Wincomplete-uni-patterns
  - -threaded
  - -rtsopts
  - '"-with-rtsopts=-N -T"'

dependencies:
  - Earley
  - GLUT
  - JuicyPixels
  - OpenGLRaw
  - base
  - containers
  - gloss
  - gloss-juicy
  - mtl
  - safe
  - transformers

library:
  source-dirs:
    - src

executables:
  giggles-is-you:
    main: Main.hs
    source-dirs:
      - app
    dependencies:
      - giggles-is-you

tests:
  test-giggles-is-you:
    main: Main.hs
    source-dirs:
      - test
    dependencies:
      - giggles-is-you
